[workspace]
authors = ["Charles O'Hanlon"]
channels = ["conda-forge"]
name = "x80_helper"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
chainlit = ">=2.9.4, <3"
openai = ">=2.14.0, <3"
azure-search-documents = ">=11.6.0, <12"
azure-core = ">=1.37.0, <2"
python-dotenv = ">=1.2.1, <2"
pandas = "*"
openpyxl = "*"
ipykernel = "*"
